#!/usr/bin/env bash
# A script to transfer a file from a client to a server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

if [ $? -eq 0 ]; then
    echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
    echo "Error occurred while transferring the file."
    exit 1
fi
