#!/usr/bin/env bash
# Server installs and configures Nginx to serve "Hello World!".

sudo apt-get update -y
sudo apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start
