#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirection for /redirect_me

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Modify the default Nginx configuration to include the redirection
sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl reload nginx
