#!/usr/bin/env bash
# Script to configure a new Ubuntu server with Nginx and a custom HTTP response header

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set up the custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test and restart Nginx
sudo nginx -t

sudo service nginx restart
