#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server
# It configures HAProxy to send traffic to web-01 and web-02 servers
# Traffic distribution is handled using a round-robin algorithm
# Ensures HAProxy can be managed via an init script

# Update the package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Define the HAProxy configuration
server_config="
frontend besthor_frontend
    bind *:80
    mode http
    default_backend besthor_backend

backend besthor_backend
    balance roundrobin
    server 176572-web-01 54.165.168.252:80 check
    server 176572-web-02 34.237.91.136:80 check
"

# Overwrite the HAProxy configuration file with the defined configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<< "$server_config"

# Enable HAProxy to be managed by init scripts
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Test the HAProxy configuration file for errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service to apply changes
sudo service haproxy restart

# Verify HAProxy status
sudo service haproxy status
