#!/usr/bin/env bash
# This short script ensures that Nginx is running and listening on port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
